version: 2.1
jobs:
  compile:
   docker:
      - image: wizardprjkt/build:kernel
   steps:
      - run:
          shell: /bin/bash
          command: |
            git clone --depth=1 https://$USERNAME:$TOKEN@github.com/strongreasons/kernel_asus_sdm636.git -b lto kernel && cd kernel
            curl https://raw.githubusercontent.com/strongreasons/cooking-kernel/circle/build.sh > run.sh
            source run.sh
          no_output_timeout : 1h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
